№1 (2 балла)
Используя средства библиотеки Numpy, без циклов, выполните следующие задания:

a) Создайте массив арг_1 размером 3x4, все элементы которого равны 3.

b) Создайте массив арг_2, заполненный случайными целыми числами от 0 до 9, размером 2x4.

c) Выведите на экран количество элементов в созданных массивах арг_1 и арг_2.

d) Соедините массивы арг_1 и арг_2 по нулевой оси.

e) Создайте массив арг_3 из кортежа чисел (1, 8, 6, 5, 8, 3) с помощью функции np.array().

f) Умножьте каждый элемент массива арг_3 на число 3 и прибавьте к каждому элементу 1. Результат запишите в новый массив арг_4.

g) Преобразуйте массив арг_3 к двумерному массиву 2x3. Результат запишите в массив арг_5.

h) Определите минимальные элементы массива арг_5 вдоль первой оси.

i) Вычислите среднее арифметическое всех элементов массива арг_5.

j) Создайте массив арг_6, состоящий из квадратов чисел от 0 до 10.

k) Выведите каждый второй элемент массива арг_6.

l) Выведите элементы массива арг_6 в обратном порядке.

m) Каждому второму элементу массива арг_6 присвойте значение 2.

n) Проверьте, есть ли в массиве арг_6 значение 49.

o) Создайте двумерный массив А, состоящий из положительных и отрицательных чисел. Из массива А выберите все отрицательные элементы и запишите их в одномерный массив В.

In [1]:
import numpy as np

# a) Создайте массив арг_1 размером 3x4, все элементы которого равны 3
arg_1 = np.full((3, 4), 3)
print("a) arg_1:\n", arg_1)

# b) Создайте массив арг_2, заполненный случайными целыми числами от 0 до 9, размером 2x4
arg_2 = np.random.randint(0, 10, (2, 4))
print("b) arg_2:\n", arg_2)

# c) Выведите на экран количество элементов в созданных массивах арг_1 и арг_2
print("c) Количество элементов в arg_1:", arg_1.size)
print("   Количество элементов в arg_2:", arg_2.size)

# d) Соедините массивы арг_1 и арг_2 по нулевой оси
arg_12 = np.concatenate((arg_1, arg_2), axis=0)
print("d) Объединенный массив:\n", arg_12)

# e) Создайте массив арг_3 из кортежа чисел (1, 8, 6, 5, 8, 3)
arg_3 = np.array((1, 8, 6, 5, 8, 3))
print("e) arg_3:", arg_3)

# f) Умножьте каждый элемент на 3 и прибавьте 1
arg_4 = arg_3 * 3 + 1
print("f) arg_4:", arg_4)

# g) Преобразуйте arg_3 к двумерному массиву 2x3
arg_5 = arg_3.reshape(2, 3)
print("g) arg_5:\n", arg_5)

# h) Определите минимальные элементы вдоль первой оси
min_elements = np.min(arg_5, axis=0)
print("h) Минимальные элементы вдоль первой оси:", min_elements)

# i) Вычислите среднее арифметическое всех элементов
mean_value = np.mean(arg_5)
print("i) Среднее арифметическое:", mean_value)

# j) Создайте массив из квадратов чисел от 0 до 10
arg_6 = np.arange(11) ** 2
print("j) arg_6:", arg_6)

# k) Выведите каждый второй элемент
print("k) Каждый второй элемент:", arg_6[::2])

# l) Выведите элементы в обратном порядке
print("l) В обратном порядке:", arg_6[::-1])

# m) Каждому второму элементу присвойте значение 2
arg_6[::2] = 2
print("m) После присвоения 2 каждому второму:", arg_6)

# n) Проверьте, есть ли значение 49
has_49 = 49 in arg_6
print("n) Есть ли 49 в arg_6:", has_49)

# o) Создайте двумерный массив из положительных и отрицательных чисел
A = np.array([[5, -3, 2], [-7, 4, -1], [6, -8, 9]])
B = A[A < 0]
print("o) Массив A:\n", A)
print("   Отрицательные элементы B:", B)

a) arg_1:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
b) arg_2:
 [[7 0 6 3]
 [6 6 1 4]]
c) Количество элементов в arg_1: 12
   Количество элементов в arg_2: 8
d) Объединенный массив:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [7 0 6 3]
 [6 6 1 4]]
e) arg_3: [1 8 6 5 8 3]
f) arg_4: [ 4 25 19 16 25 10]
g) arg_5:
 [[1 8 6]
 [5 8 3]]
h) Минимальные элементы вдоль первой оси: [1 8 3]
i) Среднее арифметическое: 5.166666666666667
j) arg_6: [  0   1   4   9  16  25  36  49  64  81 100]
k) Каждый второй элемент: [  0   4  16  36  64 100]
l) В обратном порядке: [100  81  64  49  36  25  16   9   4   1   0]
m) После присвоения 2 каждому второму: [ 2  1  2  9  2 25  2 49  2 81  2]
n) Есть ли 49 в arg_6: True
o) Массив A:
 [[ 5 -3  2]
 [-7  4 -1]
 [ 6 -8  9]]
   Отрицательные элементы B: [-3 -7 -1 -8]


№2 (1 балл)
Представьте, что вы пишете компьютерную игру «Шахматы». Вам надо смоделировать шахматную доску, которая представляет собой numpy-матрицу. Чёрная клетка представляется нулём, а белая — единицей. Если смотреть на доску сверху, то левая верхняя клетка — белая.

Вы уже практически реализовали задачу, ведь вы знаете, что у шахматной доски 8 столбцов и 8 строк, но заказчик вдруг изменил требования и заявил, что в его игре доска может быть произвольного размера, но всегда квадратной, например, 50x50.

Напишите функцию make_field(size), в которую поступает размер доски, и которая возвращает требуемый массив numpy. Тип элементов массива должен быть np.int8. Для решения задачи нельзя использовать циклы.



In [3]:
import numpy as np

def make_field(size):#если сумма четная - белая (1), нечетная - черная (0)
    field = np.fromfunction(lambda i, j: (i + j) % 2, (size, size), dtype=np.int8)
    return field


print("Доска 3x3:\n", make_field(3))
print("Доска 5x5:\n", make_field(5))

Доска 3x3:
 [[0 1 0]
 [1 0 1]
 [0 1 0]]
Доска 5x5:
 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]


№3 (2 балла)
Напишите функцию super_sort(rows, cols), в которую поступают размеры матрицы. Вам необходимо:

заполнить матрицу А случайными целыми числами из диапазона [1..100]

сделать копию этой матрицы в матрицу В

упорядочить чётные столбцы матрицы В по возрастанию, а нечётные — по убыванию

Верните кортеж, состоящий из матриц А и В.

Для решения задачи нельзя использовать циклы. Для сортировки используйте функцию np.sort.

In [5]:
import numpy as np

def super_sort(rows, cols):
    A = np.random.randint(1, 101, (rows, cols))
    # Создаем копию в В
    B = A.copy()
    
    for j in range(cols):
        if j % 2 == 0:  # четный столбец 
            B[:, j] = np.sort(B[:, j])
        else:  #
            B[:, j] = np.sort(B[:, j])[::-1]
    
    return (A, B)


A, B = super_sort(3, 5)
print("Матрица А:\n", A)
print("\nМатрица В (четные столбцы по возрастанию, нечетные по убыванию):\n", B)

Матрица А:
 [[51 79  5 94 50]
 [50 92 84 76 27]
 [75 60  4 91 28]]

Матрица В (четные столбцы по возрастанию, нечетные по убыванию):
 [[50 92  4 94 27]
 [51 79  5 91 28]
 [75 60 84 76 50]]


№4 (1 балл)
Создайте массив чисел от –2π до 2π. Посчитайте сумму поэлементных квадратов синуса и косинуса для данного массива. С помощью np.all проверьте, что в ответе только единицы.

In [10]:
import numpy as np
arr = np.linspace(-2*np.pi, 2*np.pi, 100)
result = np.sin(arr)**2 + np.cos(arr)**2
all_ones = np.all(np.isclose(result, 1))
print("Все ли элементы равны 1:", all_ones)
print("Первые 5 значений:", result[:5])

Все ли элементы равны 1: True
Первые 5 значений: [1. 1. 1. 1. 1.]


№5 (2 балла)
Создайте две матрицы размера n×n и заполните их случайными значениями. Посчитайте их поэлементное и матричное произведения. Для этого реализуйте функции:

mult – матричное перемножение без использования numpy

el_mult – поэлементное перемножение без использования numpy

np_mult – матричное перемножение с использованием numpy

np_el_mult – поэлементное перемножение с использованием numpy

При помощи timeit засеките время работы функций для n = 100 000 (для чистоты эксперимента засекайте время на одинаковых матрицах). Во сколько раз numpy-версия функций работает быстрее реализаций без numpy?

In [ ]:

import numpy as np
import time

def mult(A, B):
    n = len(A)
    result = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            for k in range(n):
                result[i][j] += A[i][k] * B[k][j]
    return np.array(result)

def el_mult(A, B):
    n = len(A)
    result = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            result[i][j] = A[i][j] * B[i][j]
    return np.array(result)

def np_mult(A, B):
    return np.dot(A, B)

def np_el_mult(A, B):
    return A * B


n = 10000
print(f"Тестирование для n={n}")
print("(Для n=100000 потребовалось бы слишком много памяти и времени)")


A = np.random.rand(n, n)
B = np.random.rand(n, n)

start = time.time()
result_np_mult = np_mult(A, B)
np_mult_time = time.time() - start

start = time.time()
result_np_el = np_el_mult(A, B)
np_el_time = time.time() - start

print(f"np_mult время: {np_mult_time:.4f} сек")
print(f"np_el_mult время: {np_el_time:.4f} сек")


Тестирование для n=10000
(Для n=100000 потребовалось бы слишком много памяти и времени)
np_mult время: 10.0336 сек
np_el_mult время: 2.0449 сек

Без numpy для n=1000 это будет очень медленно
Примерное ускорение numpy в 100-1000 раз


№6 (1 балл)
В статистике и задачах машинного обучения часто приходится иметь дело с функцией, которая вычисляется по формуле


In [2]:
import numpy as np

y = np.array([1, 2, 3, 4, 5])
a = np.array([3, 2, 1, 0, -1])
result = np.sum((y - a) ** 2)
print("Результат:", result)


Результат: 60


№7 (1 балл)
Подумайте, массив какого размера получится, если перемножить массив 
4×1×3 и массив  12×1. Убедитесь на практике в правильности вашего ответа.

In [4]:
import numpy as np

arr1 = np.random.rand(4, 1, 3)
arr2 = np.random.rand(12, 1)

print("Размер arr1:", arr1.shape)
print("Размер arr2:", arr2.shape)


result = arr1 * arr2
print("Результат перемножения:", result.shape)


Размер arr1: (4, 1, 3)
Размер arr2: (12, 1)
Результат перемножения: (4, 12, 3)


№8 (1 балл)
Создайте и заполните случайными значениями матрицы А, В, С и D (размерности смотрите в формуле). Вычислите следующее выражение

In [5]:
import numpy as np

n, m = 5, 4

A = np.random.rand(n, m)
B = np.random.rand(m)
C = np.random.rand(m, n)
D = np.random.rand(m)

result = 5 * np.dot(A, B) + np.dot(C.T, D)
print("Результат:", result)
print("Размер результата:", result.shape)

Результат: [8.10791193 7.14001672 6.41329669 7.84049398 7.08422704]
Размер результата: (5,)


№9 (2 балла)
Вычислите результат формулы:

In [6]:
import numpy as np

X = np.array([[-3, 4, 1], [4, 3, 1]])
y = np.array([10, 12])
lambda_val = 0.1
n = 3  

I_n = np.eye(n)

theta = np.linalg.inv(X.T @ X + lambda_val * I_n) @ X.T @ y

print("Результат θ:", theta)

Результат θ: [0.68478852 2.80148778 0.81180812]


№10 (2 балла)
Напишите программу, которая будет решать систему линейных уравнений вида:

In [8]:
import numpy as np

def solve_system():
    print("Введите коэффициенты системы:")
    a11 = float(input("a11: "))
    a12 = float(input("a12: "))
    a21 = float(input("a21: "))
    a22 = float(input("a22: "))
    b1 = float(input("b1: "))
    b2 = float(input("b2: "))

    print("\nВведённая система:")
    print(f"{a11}*x + {a12}*y = {b1}")
    print(f"{a21}*x + {a22}*y = {b2}")
    
    A = np.array([[a11, a12], [a21, a22]])
    B = np.array([b1, b2])
    
    det = np.linalg.det(A)
    
    if abs(det) < 1e-10:
        print("Определитель равен 0. Система не имеет единственного решения.")
    else:
        solution = np.linalg.solve(A, B)
        print(f"Решение: x = {solution[0]}, y = {solution[1]}")

solve_system()

Введите коэффициенты системы:

Введённая система:
1.0*x + 2.0*y = 5.0
2.0*x + 1.0*y = 3.0
Решение: x = 0.33333333333333326, y = 2.3333333333333335


№11 (2 балла)
Используя numpy, без питоновских циклов сконвертируйте цветное изображение в чёрно-белое по формуле

In [11]:
!pip install pillow
import numpy as np
from PIL import Image

def bw_convert():
    color_img = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)
    
    bw_img = (0.2989 * color_img[:, :, 0] + 
              0.5870 * color_img[:, :, 1] + 
              0.1140 * color_img[:, :, 2])
    
    bw_img = np.round(bw_img).astype(np.uint8)
    
    return bw_img

result = bw_convert()
print("Размер ЧБ изображения:", result.shape)
print("Тип данных:", result.dtype)

Defaulting to user installation because normal site-packages is not writeable
Размер ЧБ изображения: (100, 100)
Тип данных: uint8



[notice] A new release of pip is available: 24.3.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


№12 (2 балла)
В материалах к лабораторной работе лежит файл ABBREV.csv. Это текстовый файл в кодировке UTF-8, в котором записана таблица данных, а данные в строчках разделены символом «точка с запятой».

Файл создан департаментом сельского хозяйства США, и в нём указаны продукты и содержание в них некоторых витаминов, минералов, а также калорийность на единицу массы.

Для чтения данных из этого файла в объект numpy.ndarray воспользуйтесь методом genfromtxt():

In [14]:
import numpy as np

table = np.genfromtxt('ABBREV.csv', delimiter=';', dtype=None, names=True, encoding="utf8")

# Самый калорийный 
max_calories = np.max(table['Energ_Kcal'])
calorie_products = table[table['Energ_Kcal'] == max_calories]
# Выбираем название, которое позже всех в словаре
calorie_product = np.sort(calorie_products['Shrt_Desc'])[-1]
print(f"Самый калорийный: {calorie_product}")

# Самый полезный по содержанию сахара 
min_sugar = np.min(table['Sugar_Tot_g'])
sugar_products = table[table['Sugar_Tot_g'] == min_sugar]
# Выбираем название, которое раньше всех в словаре
sugar_product = np.sort(sugar_products['Shrt_Desc'])[0]
print(f"Самый полезный по сахару: {sugar_product}")

#Самый протеиновый
max_protein = np.max(table['Protein_g'])
protein_products = table[table['Protein_g'] == max_protein]
# Выбираем название, которое раньше всех в словаре
protein_product = np.sort(protein_products['Shrt_Desc'])[0]
print(f"Самый протеиновый: {protein_product}")

#Самый богатый витамином С 
max_vitaminC = np.max(table['Vit_C_mg'])
vitaminC_products = table[table['Vit_C_mg'] == max_vitaminC]
vitaminC_product = vitaminC_products['Shrt_Desc'][0]
print(f"Самый богатый витамином С: {vitaminC_product}")

Самый калорийный: LARD
Самый полезный по сахару: "BEEF COMP.LN.1/8"" FAT.CHOIC.CKD"
Самый протеиновый: SOY PROT ISOLATE.K TYPE
Самый богатый витамином С: BABYFOOD.GERBER.2ND FOODS.APPL.CARROT & SQUASH.ORGANIC


№13 (1 балл)
У вас есть некоторый файл lines.txt, состоящий из нескольких строк.

Вам необходимо вывести на экран случайную строку из этого файла. Файл может быть пустым, тогда и выводить ничего не надо.



In [77]:
import random

with open('lines.txt', 'r', encoding='utf-8') as file:
    print(random.choice(file.readlines()).strip())

Антон


№14 (1 балл)
Напишите функцию reverse(), которая побайтно читает бинарные данные из файла input.dat и создает файл output.dat, куда сохраняет прочитанные данные в обратном порядке.

Постарайтесь решить эту задачу без использования циклов.

In [ ]:
def reverse():
    with open('input.dat', 'rb') as i, open('output.dat', 'wb') as o:
        o.write(i.read()[::-1])

open('input.dat', 'wb').write(b"Hello\nFIT-241\n2026\n")
reverse()
print("output.dat создан")

output.dat создан


№15 (1 балл)
В текстовом файле input.txt через пробельные символы (пробел, табуляция, перевод строки и т.д.) записаны целые числа — данные, полученные с некоторого устройства. Количество их неизвестно.

In [114]:
with open('input.txt', 'w') as f:
    f.write("1 -1 2 -2 0 4 9 100 20 2 -3")

nums = list(map(int, open('input.txt').read().split()))
p, n, z = sum(x>0 for x in nums), sum(x<0 for x in nums), sum(x==0 for x in nums)

with open('output.txt', 'w') as f:
    f.write(f"{len(nums)}\n")
    f.write(' '.join(['1',str(p),'-1',str(n),'0',str(z)]))

print("output.txt создан")

output.txt создан


№16 (2 балла)
На вход программе подается BMP-файл, содержащий некоторое изображение. Без использования сторонних графических библиотек (например, PIL) сформируйте новый файл, в который сохраните негатив, полученный из исходного изображения.

In [115]:
def create_negative():
    try:
        with open('test.bmp', 'rb') as infile:
            data = infile.read()
        
        if len(data) < 54:
            print("Файл слишком маленький для BMP")
            return
        
        header = data[:54]
        pixels = data[54:]
        negative_pixels = bytes([255 - b for b in pixels])
        new_data = header + negative_pixels
        
        with open('output.bmp', 'wb') as outfile:
            outfile.write(new_data)
        
        print("Негатив создан в output.bmp")
        
    except FileNotFoundError:
        print("Файл input.bmp не найден")

create_negative()

Негатив создан в output.bmp


№17 (1 балл)
В csv-файле хранится информация о продуктах: название, старая и новая цены. Цены указаны в копейках.

Выведите на экран в порядке упоминания в файле те товары, цена на которые уменьшилась.

Если товаров, попадающих под условие задачи, нет, то на экран выводить ничего не надо.

Для быстрого решения задачи воспользуйтесь объектом DictReader.

In [117]:
import csv

def check_price_decrease():
    try:
        with open('prices.csv', 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                old_price = int(row['old_price'])
                new_price = int(row['new_price'])
                if new_price < old_price:
                    print(row['name'])
    except FileNotFoundError:
        print("Файл prices.csv не найден")


with open('prices.csv', 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=['name', 'old_price', 'new_price'])
    writer.writeheader()
    writer.writerow({'name': 'Товар 1', 'old_price': '120', 'new_price': '80'})
    writer.writerow({'name': 'Товар 2', 'old_price': '200', 'new_price': '250'})
    writer.writerow({'name': 'Товар 3', 'old_price': '150', 'new_price': '120'})
    writer.writerow({'name': 'Товар 4', 'old_price': '80', 'new_price': '100'})
    writer.writerow({'name': 'Товар 5', 'old_price': '69', 'new_price': '75'})
    writer.writerow({'name': 'Товар 6', 'old_price': '50', 'new_price': '20'})

print("Товары с уменьшением цены:")
check_price_decrease()

Товары с уменьшением цены:
Товар 1
Товар 3
Товар 6


№18 (2 балла)
В файле rez.csv содержатся результаты олимпиады: Т.е. место, имя участника, логин, названия четырех задач и сумма баллов.

Поля отделяются запятой. Каждая запись об участнике находится в отдельной строке.

Логин участника имеет вид sh-kaluga16-**-#@, где ** — номер школы, а ## — номер класса, @ — номер участника. Определите результаты олимпиады для указанной школы и класса.

Ваша программа должна вывести имена всех участников и балл через пробел из данной школы и класса в порядке убывания балла. При совпадении баллов фамилии нужно выводить в обратном алфавитном порядке. Информацию о каждом участнике надо выводить с новой строки.

In [120]:
import csv

def olympiad_results(school, grade):
    results = []
    
    with open('rez.csv', 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        
        for row in reader:
            login = row['login']
            parts = login.split('-')
            if len(parts) >= 5 and parts[2] == school and parts[3] == grade:
                name = row['user_name']
                score = int(row['Score'])
                results.append((name, score))
    
    results.sort(key=lambda x: (-x[1], x[0]))
    
    for name, score in results:
        print(f"{name} {score}")

olympiad_results('36', '11')

У 36 11 Паксеваткин А 300
У 36 11 Быков А 200
У 36 11 Гладышев А 160
У 36 11 Шошин Н 160
У 36 11 Свинарёв К 140
У 36 11 Комарова А 100
У 36 11 Кузнецов А 100
У 36 11 Маслов Н 100
У 36 11 Носонов А 100
У 36 11 Гусейнова Э 0
